---
language: python
python: '2.7'

env:
  global:
    - MOLECULEW_USE_SYSTEM=true

# Spin off separate builds for each of the following versions
# of Ansible and Linux.
matrix:
  include:
    - env:
        - MOLECULEW_ANSIBLE=2.7.15
        - MOLECULE_SCENARIO=centos-min
    - env:
        - MOLECULEW_ANSIBLE=2.7.15
        - MOLECULE_SCENARIO=centos-max
    - env:
        - MOLECULEW_ANSIBLE=2.7.15
        - MOLECULE_SCENARIO=debian-max
    - env:
        - MOLECULEW_ANSIBLE=2.7.15
        - MOLECULE_SCENARIO=debian-min
    - env:
        - MOLECULEW_ANSIBLE=2.7.15
        - MOLECULE_SCENARIO=default
    - env:
        - MOLECULEW_ANSIBLE=2.7.15
        - MOLECULE_SCENARIO=ubuntu-min
    - env:
        - MOLECULEW_ANSIBLE=2.7.15
        - MOLECULE_SCENARIO=fedora
    - env:
        - MOLECULEW_ANSIBLE=2.7.15
        - MOLECULE_SCENARIO=opensuse
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=centos-min
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=centos-max
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=debian-max
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=debian-min
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=default
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=ubuntu-min
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=fedora
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=opensuse
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=ubuntu-max-go-eol

# Require the standard build environment
sudo: required

# Require Ubuntu 16.04
dist: xenial

# Require Docker
services:
  - docker

install:
  # Install dependencies
  - ./moleculew wrapper-install

  # Display versions
  - ./moleculew wrapper-versions

script:
  - ./moleculew test --scenario-name=$MOLECULE_SCENARIO

cache:
  directories:
    - $HOME/.moleculew

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
