name: Tests

on:
  push:
    branches:
      - master
  pull_request: {}

env:
  MOLECULEW_USE_SYSTEM: 'true'
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  test:
    name: Molecule test
    runs-on: ubuntu-18.04

    strategy:
      max-parallel: 3
      matrix:
        architecture:
          - amd64
        ansible-version:
          - '2.9.1'
        molecule-scenario:
          - centos-min
          - centos-max
          - debian-max
          - debian-min
          - default
          - ubuntu-min
          - fedora
          - opensuse
        include:
          - architecture: arm
            ansible-version: '2.9.1'
            molecule-scenario: ubuntu-arm32v7
          - architecture: arm64
            ansible-version: '2.9.1'
            molecule-scenario: ubuntu-arm64v8
          - architecture: amd64
            ansible-version: '2.8.16'
            molecule-scenario: default

    env:
      MOLECULEW_ANSIBLE: ${{ matrix.ansible-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Cache Molecule
        id: molecule-cache
        uses: actions/cache@v2
        with:
          path: ~/.moleculew
          key: Ansible-${{ matrix.ansible-version }}-${{ hashFiles('.moleculew/**') }}

      - name: Install dependencies
        if: steps.molecule-cache.outputs.cache-hit != 'true'
        run: ./moleculew wrapper-install

      - name: Dependency versions
        run: ./moleculew wrapper-versions

      - name: Set up QEMU
        if: matrix.architecture != 'amd64'
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: ${{ matrix.architecture }}

      - name: Molecule test
        run: ./moleculew test --scenario-name=${{ matrix.molecule-scenario }}

      - name: Compact cache
        if: steps.molecule-cache.outputs.cache-hit != 'true'
        run: find ~/.moleculew -name '__pycache__' -exec rm -rf {} +

  test-all:
    if: ${{ always() }}
    name: Test (matrix)
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - name: Check test matrix status
        run: "[[ '${{ needs.test.result }}' == 'success' ]] || exit 1"
